application:
  runtimeManifest:
    packages:
      nextjs-citisignal-integration:
        license: Apache-2.0
        actions:
          api-mesh-query-content:
            function: src/api-mesh/actions/api-mesh-query-content/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              MESH_ID: $MESH_ID
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
